---
title: "Formula Sheet for Minitab"
author: "Neil J. Hatfield"
date: "`r paste('Last Updated:', format(Sys.Date(), '%B %d, %Y'))`"
output: 
  pdf_document
geometry: left=1in,right=1in,top=1in,bottom=1in
urlcolor: blue
header-includes: 
  \usepackage{subfig}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Use this guide as a resource for getting additional values that are not possible in Minitab.

I will draw upon the output of the omnibus test and Tukey's Post Hoc as much as possible here.

# Omnibus Effect Sizes

There are three key measures here "eta-sq." ($\eta^2$), "epsilon-sq." ($\epsilon^2$), and "omega-sq." ($\omega^2$).

## "Raw" Values (Good for One-way)

For Eta-sq., use the "R-sq" value reported in the Model Summary of the output.

For Epsilon-sq., use the "R-sq(adj)" value reported in the Model Summary.

Ignore both "S" and "R-sq(pred)".

For Omega-sq., use the following: $$\omega^2=\frac{SSQ_{\text{factor}}-\left(df_{\text{factor}}\cdot MS_{\text{Error}}\right)}{SSQ_{\text{Total}} + MS_{\text{Error}}}$$

You should be able to get all of these values from the ANOVA table. Make sure that you use as many decimals as possible to minimize the propagation of rounding errors.

## "Partial" Values (for models multiple terms)

In the following formulas, *F* will refer to the *F* ratio for the particular term you are testing, \(df_{\text{num}}\) is the *degrees of freedom* for the numerator for the selected *F* ratio; \(df_{\text{denom}}\) will be the *degrees of freedom* for the denominator used in the *F* ratio.

\[\eta^2_p=\frac{F\cdot df_{\text{num}}}{F\cdot df_{\text{num}}+df_{\text{denom}}}\]
\[\epsilon^2_p=\frac{(F-1)\cdot df_{\text{num}}}{F\cdot df_{\text{num}}+df_{\text{denom}}}\]
\[\omega^2_p=\frac{(F-1)\cdot df_{\text{num}}}{F\cdot df_{\text{num}}+N - df_{\text{num}}}\]

Where *N* is the sum of the *degrees of freedom* across all rows of your table plus 1 (for the Grand Mean).

# Post Hoc Effect Sizes

To calculate these values you will need to get the following information:

+ Descriptive Statistics
  1) Stat Menu -> Basic Statistics -> Display Descriptive Statistics...
  2) Place the response in the Variables box and your factor in the By variables box
  3) Click on the Statistics... button
  4) Select just Variance and N nonmissing and click OK
  5) Click OK
+ Pairwise Differences
  1) Stat Menu -> ANOVA -> One-way...
  2) Place the response in the Response box and the factor in the factor box
  3) Click on the Comparisons... button
  4) Select Tukey and check the Tests box under Results; click OK.
  5) Click OK

You'll use values from these two outputs to calculate values.

## Cohen's *d*

To calculate Cohen's *d* you will need the following:

+ From the Descriptive Statistics output
  - The *Sample Arithmetic Variance* for both groups
  - The sample size for both groups
+ From the Tukey Tests for Differences of Means Output (ANOVA)
  - Difference of Means

To match what is going on via the `DescTools::CohenD` function as of 3/30/23, you will need to first calculate the *[Weighted] Pooled Standard Deviation* with the following formula:
\[SD_{\text{wpd}}=\sqrt[2]{\frac{(n_1-1)SAV(\text{group 1})+(n_2-1)SAV(\text{group 2})}{n_1+n_2-2}}\]

Once you have calculated this value, you get Cohen's *d* via
\[d=\frac{\text{diff in means}}{SD_{\text{wpd}}}\]

## Hedge's *g*

For Hedge's *g*, you will need:

+ Cohen's *d*
+ The value of the scale correction:
\[c=1-\frac{3}{4\left(n_1+n_2\right)-9}\]

Then Hedge's *g* is then calculated as \(g=d*c\).

## Probability of Superiority

You will need to first calculate Cohen's *d*. Then go to the [ANOVA Helper1 app](https://rstudio-connect.tlt.psu.edu:3939/content/334) (https://rstudio-connect.tlt.psu.edu:3939/content/334) and enter *d* into the appropriate field. NOTE: you will need to log into PSU's VPN if you are off-campus to access this app.

# Post Hoc Methods Not in Minitab

Minitab limits which post hoc methods you can do. I'm not going to re-invent the wheel for how to perform these methods. However, I will point you towards where you can see how to do these.

## Bonferroni Style

In these methods, you are not adjusting any *p*-values, rather you are going to adjust your Unusualness Thesholds. See Section 5.2 of Oehlert.

## Adjusting Methods

These methods would be similar to Tukey's HSD, which Minitab will do for you. Section 5.4 of Oehlert is the key section you'll need to reference.

+ REGWR--Section 5.4.4 of Oehlert
+ SNK--Section 5.4.5 of Oehlert

The major challenge is getting the appropriate value of the *Studentized Range* for both REGWR and SNK methods. To get this value, you will need to make use of the [ANOVA Helper1 app](https://rstudio-connect.tlt.psu.edu:3939/content/334) (https://rstudio-connect.tlt.psu.edu:3939/content/334). NOTE: you will need to log into PSU's VPN if you are off-campus to access this app. Once there, you will need to enter in

+ The Overall Type I Error Rate,
+ The number of groups you're comparing (this would be *k* in Oehlert for REGWR/SNK), and
+ The *degrees of freedom* for the Residuals/Error term from the ANOVA table.

# Scheffé Methods

For dealing with contrasts, you are going to want to reference Chapter 4 of Oehlert. Let me know what additional tools you need. However, I'm going to encourage you to seriously consider using R instead of doing all of this by hand.

