---
title: "Course Project Specifications"
author: "Neil J. Hatfield"
date: ""
output: pdf_document
geometry: left=0.75in,right=0.75in,top=0.5in,bottom=0.5in
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

The purpose of the Course Project is multifaceted. On the one hand, you get to put into practice (and show off) your understandings of the course material in an authentic way. That is to say, there is little room to hide what you do and do not understand. On the other, you will further practice your communication and teamwork skills that are vital to you getting a job and becoming a top-notch statistician, data scientist, or other wielder of statistical tools.

The course project is fairly straightforward with two options: 

+ __Option 1__: Design and carryout an experiment to collect data and then analyze that data to answer your research question.
+ __Option 2__: Find and adopt a data set that works for your research question (you must describe the way the data was collected and for what original purpose) and then analyze the data to answer your research question.

In either option, you will be submitting a single report (including an Executive Summary) at the end of the semester.

Since this is a project for our ANOVA class, your central analysis __must__ come from the ANOVA Toolkit. You may not propose a regression project. If you are proposing multiple analyses, the primary one should be ANOVA. Any secondary analyses are up to you.

## Details 

Let's take a look at the details a bit more closely:

1) Begin thinking about ideas and teams (GP #1)

2) Teams get formed
    A) Neil will help people to form teams of roughly 2-4 people. Final team formation will be joint enterprise between the class and Neil.
    B) At the end of the semester, each member of a team will be responsible for anonymously grading each team member as well as themselves.
3) Develop a Statistical Research Question
    A) As a team, develop a statistical research question.
    B) You will have to get approval from Neil (GP #2)
4) Develop your Study/Experiment
    A) As a team, develop your experiment or observational study (as the case might be)
    B) You will have to get your plan approved by Neil (GP #3) 
    C) Special Note--Involvement of Human and Animal Subjects
        i) In the event you need to use either Humans or Animals subjects, you will need to have your study scrutinized carefully in coordination with Neil.
        ii) If you need to go down this route, your timetable is now ASAP.
        iii) Data may NOT be collected until after IRB approval is secured.
5) Collect your Data
    A) As a team, carry out your experiment or observational study to collect your data.
    B) If you are adopting data, you need to identify whether any Data Sharing Agreements need to be signed. If so, you need to work with Neil so that we can get you access to the data. DO NOT FILL OUT ANY DATA AGREEMENT ON YOUR OWN.
    C) I have limited funds which may help to defray costs.
6) Analyze your Data
    A) Clean your Data
    B) Write your Data Narrative
    C) Carry out the appropriate method(s) of analysis from the __ANOVA toolkit__. (Note: you can't use a regression model for this project)
6) Write your report
    A) Structure
        1) Executive Summary (2 page max)
        2) Introduction
        3) Literature Review
        4) Methods
            a) Describe the experiment/study
            b) Describe the statistical methods you used
            c) Describe the sample (if applicable)
        5) Results
        6) Discussion
        7) References
        8) Code Appendix
    B) Make sure that you answer your SRQ.
7) Complete Peer Evaluations (GP #4)
8) Submit your Project Report (GP #5).

## Potential Topics

You are only bound by four things: 1) ethics, 2) what you can complete (i.e., collect and analyze) in the remaining time this semester, 3) the interests of your team, and 4) what you can afford.

I will not approve any SRQ and subsequent study design (experimental or observational) that I believe to be ethically questionable. The same is true for using data obtained by someone else. I will do my best to help your team refine your SRQs into something that you can explore this semester and I will give you pointers on your study design. Try to draw from your experiences for inspiration.

I have a few suggestions for projects that I would like to see students pick up and complete this semester.

### Cost of Voting with Voter ID Laws

Much of the focus on Voter ID laws is on their discriminatory impacts on minorities. My curiosity with these laws is different: I want to know more about the *cost* to vote in a federal/state election. There are at least two ways to opertionalize cost here: what is the minimal cost for a typical voter to obtain the ID; what is the maximal cost for a typical voter to obtain the ID? Further, I would like to know whether the party in power of each state's legislature and governor's office has an impact on these costs.

Note: because of the multiple ways to operationalize cost here, several different groups may explore this issue...provide they have different operationalizations.

### Wisconsin Fast Plants and Fertilizer

Several years ago, I had a couple of students do an Honors project where they looked at the impacts of different kinds of fertilizer on different species of Wisconsin Fast Plants. (They primarily looked at plant height.) However, they ran into a couple of issues that confounded their results. Their original study could be re-done or you could propose something new. For example, some fertilizers don't impact plant height, but rather plant "bushy-ness". 

### Oreos

I'm always open to new explorations of Oreos, especially since they keep coming out with different sizes (Thin, Regular, Double Stuf, Mega Stuf, the Most Stuf) and flavors. What are the differences in the amount of créme filling? What are the differences in the ratios of créme filling to wafer cookies?


### Additional Project Ideas

Here are some ideas that have been done by students in the past:

| Factors | Response |
|---------------------------------------------------------------------------------------------|----------------------------------------------------------|
| seat height, generator, tire pressure | bike course completion time/pulse rate |
| popcorn brand, batch size, popcorn to oil ratio | yield of popcorn |
| amount of yeast, amount of sugar, liquid type, rise temp, rise time | quality of bread |
| hours of illumination, water temp, specific gravity of water | growth rate of algae |
| blending speed, amount of water, water temp, soaking time | blending time for soy beans |
| width/height ratio of balsa wood, slant angle, dihedral angle, weight added, wood thickness | flight length for model airplane |
| type of drink, number of drinks, rate of drinking, hours after last meal | time to get ball through maze |
| stamp type, zip code, time of day when mailed | days required for delivery of letter |
| distance to target, type of gun, type of powder | number of shot penetrating 1ft diameter circle on target |
| amounts of cooking wine, oyster sauce, sesame oil | taste of stewed chicken |
| ambient temp, choke setting, number of charges | number of kicks to start motorcycle |
| amounts of flour, eggs, milk | taste of pancakes (consensus of housemates) |
| brand of tape deck, bass level, treble level, synthesizer | clearness and quality of sound |
| child's weight, spring tension, swing orientation | number of swings and duration of an infant swing |
| orientation of football, kick, steps taken prior, shoe type | distance football is kicked |
| amount of detergent, bleach, fabric softener | ability to remove oil and grape juice stains |
| weight of bowling ball, spin, bowling line | bowling pins knocked down |
| freq. of watering, use of plant food, temp of water | plant growth rate |
| temp of gas chromatograph column, tube type, voltage | size of unwanted droplet |
| concentration of lactose crystal, crystal size, rate of agitation | spreadability of caramel candy |
| proportional band, manual reset, regulator pressure | sensitivity of pneumatic valve control system |
| temp, nitrate concentration, amount of added preservatives | nitrate concentration in sewage |
| pH, dissolved oxygen content of water, temp | extent of iron corrosion |
| amperage, contact tube height, travel speed, edge preparation | quality of weld |
| brand, mess type, liquid amount, amount of towels used | quality of paper towel clean up |
| type of OS, amount of RAM available, language used, parallel or serial processing | Computation Speed |
| oven temp, baking time | Quality of cake |
| brand of pop/soda, type of candy | volume of displaced foam |
| species of Wisconsin Fast Plant, fertilizer type, light conditions | height of plant |
| Minecraft Character Handedness, Shooting Hand, Type of Bow | Shot power |
