# Revisiting the Song Knowledge Study

I want to return to our Song Knowledge study and the issue we have with heteroscedasticity. As mentioned in class and earlier in this guide, I would recommend a variance stabilizing transformation. Something to note here is that figuring out the appropriate transformation can be a bit guess-and-test. The one caution to transformations is that our ANOVA results on transformed data are only valid for the *transformed* data, not the original response.

## Initial Transformation Ideas

This is where our knowledge of the context becomes useful. Our response (the score) is generated by *counting* the number of correct answers ("successes") out of 20 trials. I've used leading language here to hopefully bring to mind a few useful ideas.

+ Each artist/title line could be thought of as a Bernoulli trial where a person either gets the element correct (1) or incorrect (0).
+ We could replace the score with the proportion correct out of 20 trials (i.e., make the response a Binomial).
+ We could think about the score explicitly as a count (i.e., treat the response as Poisson).

This approach to transformation works when there appears to be a relationship between the value of the cell means (baseline + factor effect) and the (group-level) variance. As mentioned in Oehlert, this approach works well when we have the value of the *SAM* relative large to the *SASD*. For our data collection, \(\mathcal{X}\), we have \(SAM(\mathcal{X})/SASD(\mathcal{X})=`r round(mean(songData$Score)/sd(songData$Score), digits=2)`\), which suggests that we might not have the best of luck with these transformations and would need to try an alternative approach.

### Alternative Transformations

Alternatively, we can look to use a Power transformation provided that all of our data are positive (i.e., greater than zero). We could use either the regression method or the Box-Cox method to determine the appropriate power transformation. These transformations don't have much effect unless the ratio between the extremes is greater than ~4. In our data, the value of this ratio is \(Max(\mathcal{X})/Min(\mathcal{X})=`r round(max(songData$Score)/min(songData$Score), 2)`\), which suggests that we might have luck.

## Tranforming the Data and Fitting New Models

I'm going to demonstrate four transformations: one for converting the scores to a proportion, one for treating the score as a count, and two power transformations. The following code shows how I'm going to transform the data.

```{r transData, echo=TRUE}
# Example Code--Transform Scores
## Binomial (adjProportion), Poisson (adjCount),
## Power (powerTrans), and Box Cox (boxCox)
## I used the regression method described in Oehlert (pg 128)

sgm <- psych::geometric.mean(songData$Score)

songData <- songData %>%
  mutate(
    adjProportion = asin(sqrt(Score / 20)),
    adjCount = sqrt(Score),
    powerTrans = sign(0.2386)*Score^(0.2386),
    boxCox = (Score^0.222 - 1) / (0.222 * sgm^(0.222 - 1))
  )

# Fit the New Models ----
songPropModel <- aov(
  formula = adjProportion ~ Year,
  data = songData
)

songCountModel <- aov(
  formula = adjCount ~ Year,
  data = songData
)

songPowerModel <- aov(
  formula = powerTrans ~ Year,
  data = songData
)

songBCModel <- aov(
  formula = boxCox ~ Year,
  data = songData
)

```

## Check Assumptions

After we fit a transformation, we MUST reassess *all* assumptions to ensure that the transformation did not introduce/uncover a problem.

### Gaussian Assumption

Figure \ref{fig:qqPlots2} shows the QQ plots for our four transformations. The good news is that both show that the residuals using the transformed data still satisify the Gaussian assumption.

```{r qqPlots2, fig.cap="QQ Plots", fig.subcap=c("Adj. Proportion", "Adj. Count", "Power Transformation", "Box-Cox"), fig.ncol=2, out.width="50%",echo=TRUE, fig.pos="H"}
## Adj. Proportion
car::qqPlot(
  x = songPropModel$residuals,
  distribution = "norm",
  envelope = 0.90,
  id = FALSE,
  pch = 20,
  ylab = "Residuals"
)

# Adj. Count
car::qqPlot(
  x = songCountModel$residuals,
  distribution = "norm",
  envelope = 0.90,
  id = FALSE,
  pch = 20,
  ylab = "Residuals"
)

# Power
car::qqPlot(
  x = songPowerModel$residuals,
  distribution = "norm",
  envelope = 0.90,
  id = FALSE,
  pch = 20,
  ylab = "Residuals"
)

# Box-Cox
car::qqPlot(
  x = songBCModel$residuals,
  distribution = "norm",
  envelope = 0.90,
  id = FALSE,
  pch = 20,
  ylab = "Residuals"
)

```

### Homoscedasticity

Again, we'll make use of strip charts for assessing this assumption. This is the assumption that we're attempting to fix, so we will want to make sure that look carefully here. We will also want to refer back to Figure \ref{fig:stripCharts} to see what we originally had.

```{r stripCharts2, fig.cap="Strip Charts", fig.subcap=c("Adj. Proportion", "Adj. Count", "Power Transformation", "Box-Cox"), fig.ncol=2, out.width="50%", echo=TRUE, fig.pos="H"}

# Adj. Proportion
ggplot(
  data = data.frame(
    residuals = songPropModel$residuals,
    fitted = songPropModel$fitted.values
  ),
  mapping = aes(x = fitted, y = residuals)
) +
  geom_point(size = 2) +
  theme_bw() +
  xlab("Fitted values") +
  ylab("Residuals")

# Adj. Count
ggplot(
  data = data.frame(
    residuals = residuals(songCountModel),
    fitted = fitted(songCountModel)
  ),
  mapping = aes(x = fitted, y = residuals)
) +
  geom_point(size = 2) +
  theme_bw() +
  xlab("Fitted values") +
  ylab("Residuals")

# Power Transformation
ggplot(
  data = data.frame(
    residuals = residuals(songPowerModel),
    fitted = fitted(songPowerModel)
  ),
  mapping = aes(x = fitted, y = residuals)
) +
  geom_point(size = 2) +
  theme_bw() +
  xlab("Fitted values") +
  ylab("Residuals")

# Box-Cox
ggplot(
  data = data.frame(
    residuals = residuals(songBCModel),
    fitted = fitted(songBCModel)
  ),
  mapping = aes(x = fitted, y = residuals)
) +
  geom_point(size = 2) +
  theme_bw() +
  xlab("Fitted values") +
  ylab("Residuals")

```

The adjusted proportion (upper left of Figure \ref{fig:stripCharts2}) does not show much, if any, improvement on the assumption of homoscedasticity. However, this is some improvement for the other three transformations.

### Independence of Observations

Provided you did not use a transformation that introduces independence (e.g., add half of the previous case's value), then this assumption should still be satisfied. 

## Results

For this I'm only going to report the results of the Box-Cox transformation.

```{r bcANOVATable, echo=TRUE}
parameters::model_parameters(
  model = songBCModel,
  effectsize_type = c("eta", "omega", "epsilon") # Effect sizes
) %>%
  knitr::kable(
    digits = 4,
    col.names = c(
      "Source", "SS", "df", "MS", "F", "p-value",
      "Eta Sq.", "Omega Sq.", "Epsilon Sq."),
    caption = "ANOVA Table for Spring '23 Song Knowledge Study with Box-Cox Transformation",
    booktabs = TRUE,
    align = c("l", rep("c", 8))
  ) %>%
  kableExtra::kable_styling(
    font_size = 10,
    latex_options = c("HOLD_position")
  )

```

Notice that the results of Table \ref{tab:bcANOVATable} are not that different from those in Table \ref{tab:songANOVATable}. This suggests that 
